# Generated by Django 4.1.4 on 2023-01-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='correct_answer_number',
            field=models.IntegerField(default=0),
        ),
    ]
