# Generated by Django 4.1.4 on 2023-01-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_response_correct_answer_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Antworten',
        ),
    ]
